server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: filebox
    password: fS7DHXQJxCkdzPmX
    url: jdbc:mysql://127.0.0.1:13306/filebox?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1200000
      connection-timeout: 20000
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
      resolve-lazily: true

file:
  storage:
    location: /share/fileBox/upload

logging:
  level:
    com.zorroe.cloud: debug
